
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "=1.11.1"

[[constraint]]
  name = "github.com/blang/semver"
  version = "=3.5.0"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "=1.19.1"

[[constraint]]
  branch = "master"
  name = "github.com/metaleap/go-util"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/tg/gosortmap"

[[constraint]]
  branch = "master"
  name = "github.com/vektra/errors"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
