version: 2
jobs:
  build:
    working_directory: /go/src/github.com/opencontrol/compliance-masonry
    docker:
      - image: golang:1.10-alpine
    steps:
      - run:
          name: Install Git
          command: apk add --no-cache bash gcc git musl-dev curl
      - checkout

      - run:
          name: Build the compliance-masonry program
          command: go build cmd/compliance-masonry/compliance-masonry.go
      - run:
          name: Build the masonry program
          command: go build cmd/masonry/masonry.go
      - run:
          name: Run tests
          command: ./.circleci/coverage.sh
      - run:
          name: Send results to Codecov
          shell: /bin/bash
          command: bash <(curl -s https://codecov.io/bash)
