version: 2
jobs:
  build:
    working_directory: /go/src/github.com/opencontrol/compliance-masonry
    docker:
      - image: golang:1.15
    steps:
      - checkout

      - run:
          name: Build the compliance-masonry program
          command: go build cmd/compliance-masonry/compliance-masonry.go
      - run:
          name: Build the masonry program
          command: go build cmd/masonry/masonry.go
      - run:
          name: Run tests
          command: ./.circleci/coverage.sh
      - run:
          name: Send results to Codecov
          shell: /bin/bash
          command: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            if [[ ! -z ${CIRCLE_TAG} ]]; then
              echo "TAG: ${CIRCLE_TAG}"
              curl -sL https://git.io/goreleaser | bash
            fi

deployment:
  trigger_tag:
    tag: /.*/
